name: ${project.artifactId}
version: ${project.version}
api-version: 1.18
author: ItsJustMiaouss
website: https://github.com/ItsJustMiaouss/NextCommand
main: com.itsjustmiaouss.nextcommand.NextCommand
commands:
  nextcommand:
    description: Main plugin command
    aliases:
      - nc
      - nextc
  broadcast:
    description: Send a message to connected players
  feed:
    description: Set max food level and max saturation to player
  heal:
    description: Set max heal to player
  fly:
    description: Toggle fly for player
  hat:
    description: Place a block or an item on player's head
  invsee:
    description: See player's inventory
  setspawn:
    description: Set the spawn point
  spawn:
    description: Go to spawn point
  ping:
    description: Get the player ping
  setwarp:
    description: Save warp location
  warp:
    description: Teleport to a warp
  delwarp:
    description: Delete a warp